const usuarios = {
  usuarios: [
    {
      id: 1,
      Nombres: 'Jorge ',
      apellidos: 'Guzman Allende',
      Correo: 'admin@gmail.com',
      password: '654321',
      foto: '',
      DNI: '87654321',
      type: 'admin',
    },
    {
      id: 2,
      Nombres: 'Luis Enrique',
      apellidos: 'Rojas Sanchez',
      Correo: 'lenriquers12@gmail.com',
      password: '123456',
      foto: 'https://images.generated.photos/9q0t68GuoBaa5oDdUFKwau6DTiK8QBQBj-d04m8zDqY/rs:fit:512:512/wm:0.95:sowe:18:18:0.33/czM6Ly9pY29uczgu/Z3Bob3Rvcy1wcm9k/LnBob3Rvcy92M18w/MjI5NDA2LmpwZw.jpg',
      DNI: '12345678',
      type: 'user',
    },
  ],
};

const eventos = {
  eventos: [
    {
      _id: 1,
      title: 'Salsa Colombiana',
      img: 'https://live.staticflickr.com/3815/11566089773_767a3c6f27_b.jpg',
      ticketImg: '',
      lowestPrice: 80.0,
      category: 'Conciertos',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-14',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 80,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 120,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 160,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-15',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 80,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 120,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 160,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 3,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 2,
      title: 'Teatro chino',
      img: 'https://c.pxhere.com/photos/db/b2/opera_chinese_stage_act_culture_traditional_makeup_performance-1261363.jpg!d',
      ticketImg: '',
      lowestPrice: 45.0,
      category: 'Teatro',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-16',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 45,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 60,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 75,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-17',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 45,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 60,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 75,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 3,
      title: 'Rock Alternativo',
      img: 'https://live.staticflickr.com/7908/32393579967_9b4471fc20_3k.jpg',
      ticketImg: '',
      lowestPrice: 90.0,
      category: 'Conciertos',
      ageRestriction: 'allAges',
      description:
        'Luego de 2 años sin tener un concierto presencial, Adrián Bello vuelve con toda su banda y se presenta en el Centro de Convenciones Barranco. Todo lo que sube, Brasil, Explosion,Escondidos, entre otros, son algunos de los temas que el artistapodrá por fin tocar en vivo en un reencuentro muy especial con su público',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-13',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 60,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 90,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 120,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-14',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 60,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 90,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 120,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: 'Av. República de Panamá 220, Barranco',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 4,
      title: 'Vuelve el voley',
      img: 'https://live.staticflickr.com/65535/48494810371_dbe87c2d6a_h.jpg',
      ticketImg: '',
      lowestPrice: 25.0,
      category: 'Deportes',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-14',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 25,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 50,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 75,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-15',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 25,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 50,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 75,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 5,
      title: 'Eva Ayllon - en vivo',
      img: 'https://live.staticflickr.com/8568/28375523481_b1cc3b1d69_k.jpg',
      ticketImg: '',
      lowestPrice: 60.0,
      category: 'Conciertos',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-13',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 60,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 90,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 120,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-14',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 60,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 90,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 120,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 6,
      title: 'Conferencia Samsung - 2022',
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Samsung%27s_Virtual_Reality_MWC_2016_Press_Conference_%2826666393696%29.jpg/1200px-Samsung%27s_Virtual_Reality_MWC_2016_Press_Conference_%2826666393696%29.jpg',
      ticketImg: '',
      lowestPrice: 50.0,
      category: 'Tecnología',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-17',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 50,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 70,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 90,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-18',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 50,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 70,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 90,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 7,
      title: 'Wiñaypacha',
      img: 'https://larepublica.pe/resizer/dQP-3xWkUCy6mPmReHtaIiz76kw=/1250x735/top/smart/cloudfront-us-east-1.images.arcpublishing.com/gruporepublica/NUPZJOLKARFNPNKV2LIJGIOSEQ.jpg',
      ticketImg: '',
      lowestPrice: 30.0,
      category: 'Cine',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-11',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 30,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 50,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 70,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-12',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 30,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 50,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 70,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 8,
      title: 'Coldplay en Perú',
      img: 'https://live.staticflickr.com/3677/14292292232_af0fc69ccc_h.jpg',
      ticketImg: '',
      lowestPrice: 180.0,
      category: 'Conciertos',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-15',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 180,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 260,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 500,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-16',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 180,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 260,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 500,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'active',
    },
    {
      _id: 9,
      title: 'La salud psicológica en los tiempos del Covid - 19',
      img: 'https://i.ytimg.com/vi/NvpGEjE1xU0/maxresdefault.jpg',
      ticketImg: '',
      lowestPrice: 45.0,
      category: 'Salud y Bienestar',
      ageRestriction: 'allAges',
      description:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborumnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentiumoptio, eaque rerum! Provident similique accusantium nemo autem.',
      infoExtra: 'info',
      currency: 'S/.',
      dates: [
        {
          _id: 123466,
          date: '2022-02-14',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3333,
              type: 'General',
              price: 45,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3334,
              type: 'VIP',
              price: 70,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3335,
              type: 'Platinum',
              price: 90,
              quantity: 10,
              sold: 0,
            },
          ],
        },
        {
          _id: 123644,
          date: '2022-02-15',
          startHour: '21:00',
          endHour: '22:00',
          isEditable: true,
          ticketCategories: [
            {
              _id: 3336,
              type: 'General',
              price: 45,
              quantity: 30,
              sold: 0,
            },
            {
              _id: 3337,
              type: 'VIP',
              price: 70,
              quantity: 20,
              sold: 0,
            },
            {
              _id: 3338,
              type: 'Platinum',
              price: 95,
              quantity: 10,
              sold: 0,
            },
          ],
        },
      ],
      city: 'Lima',
      address: '',
      refference: '',
      idOwner: 2,
      ownerName: 'Concerts',
      state: 'inactive',
    },
  ],
};

const tickets = {
  tickets: [
    {
      id: 1,
      idUsuario: 2,
      evento: [
        {
          idEvento: 2,
          typeTicket: 'General',
          dateEvent: '2022-02-16',
          quantity: 2,
        },
      ],
      idTransaction: '1',
    },
  ],
};

const sales = {
  sales: [
    {
      id: 1,
      token: '12345678',
      numberTransaction: 'ASD54F1V8WO6H4H5',
      client: 'Luis Enrique',
      cardNumber: '369874521123654',
      paymentDate: '2022-02-15',
      cardType: 'VISA',
      idUser: 2,
      totalFare: 90,
    },
  ],
};

const shopCart = {
  cart: [
    {
      id: 1,
      title: 'Salsa Colombiana',
      img: 'https://live.staticflickr.com/3815/11566089773_767a3c6f27_b.jpg',
      city: 'Lima',
      dateId: 123466,
      date: '2022-02-14',
      hour: '21:00',
      typeTicket: 'Platinum',
      price: 120.0,
      amount: 1,
      categoryId: 3335,
      idUsuario: 2,
      idEvento: 1,
    },
    {
      id: 2,
      title: 'Rock Alternativo',
      img: 'https://live.staticflickr.com/7908/32393579967_9b4471fc20_3k.jpg',
      city: 'Lima',
      dateId: 123644,
      date: '2022-02-14',
      hour: '21:00',
      typeTicket: 'VIP',
      price: 90.0,
      amount: 2,
      categoryId: 3337,
      idUsuario: 2,
      idEvento: 3,
    },
    {
      id: 3,
      title: 'Vuelve el voley',
      img: 'https://live.staticflickr.com/65535/48494810371_dbe87c2d6a_h.jpg',
      city: 'Lima',
      dateId: 123466,
      date: '2022-02-14',
      hour: '21:00',
      typeTicket: 'General',
      price: 50.0,
      amount: 1,
      categoryId: 3333,
      idUsuario: 2,
      idEvento: 4,
    },
  ],
};

const slides = {
  slides: [
    {
      id: 1,
      title: 'Coldplay en Perú',
      date: '2022-02-15',
      order: 3,
      img: 'https://live.staticflickr.com/3677/14292292232_af0fc69ccc_h.jpg',
      eventId: 8,
    },
    {
      id: 2,
      title: 'Eva Ayllon - en vivo',
      date: '2022-02-13',
      order: 1,
      img: 'https://live.staticflickr.com/8568/28375523481_b1cc3b1d69_k.jpg',
      eventId: 5,
    },
    {
      id: 3,
      title: 'Conferencia Samsung - 2022',
      date: '2022-02-17',
      order: 2,
      img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Samsung%27s_Virtual_Reality_MWC_2016_Press_Conference_%2826666393696%29.jpg/1200px-Samsung%27s_Virtual_Reality_MWC_2016_Press_Conference_%2826666393696%29.jpg',
      eventId: 6,
    },
  ],
};

const creditCard = {
  creditCard: [
    {
      numberCard: '369874521123654',
      expiryDate: '10/25',
      CVV: '123',
      name: 'Renzo',
      lastname: 'Manrique',
      email: 'renzo.manrique@gmail.com',
    },
    {
      numberCard: '369874521123655',
      expiryDate: '10/26',
      CVV: '789',
      name: 'Pedro',
      lastname: 'Perez',
      email: 'pedro.perez@gmail.com',
    },
  ],
};

const mockDB = {
  usuarios,
  eventos,
  tickets,
  sales,
  shopCart,
  slides,
  creditCard,
};

export default mockDB;
